services:
  # api-gateway:
  #   ports:
  #     - "50051:50051"
  #   networks:
  #     - mercypher-backend
  ####
  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "50054:50054"
    depends_on:
      - user-db
    env_file:
      - ./user-service/.env
    environment:
      - ENVIRONMENT=docker
    networks:
      - mercypher-backend
  user-db:
    container_name: user-db
    image: postgres
    volumes:
      - E:/AbelovaGrupa/Projekti/Mercypher/deployment/volumes/user-db:/user-service/path
    env_file:
      - ./user-service/.env
    ports:
      - "5432:5432"
    networks:
      - mercypher-backend

  session-service:
    container_name: session-service
    build:
      context: ./session-service
      dockerfile: Dockerfile
    ports:
      - "50055:50055"
    depends_on:
      - session-db
    env_file:
      - ./session-service/.env
    environment:
      - ENVIORMENT=docker
    networks:
      - mercypher-backend

  session-db:
    container_name: session-db
    image: postgres
    volumes:
      - E:/AbelovaGrupa/Projekti/Mercypher/deployment/volumes/session-db:/session-service/path
    env_file:
      - ./session-service/.env

    networks:
      - mercypher-backend

  kafka: 
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
     - ./kafka/.env
    post_start: # !!! 
      - command: kafka-topics --create --topic "chat-messages-v1" --if-not-exists --bootstrap-server localhost:9092
    networks:
      - mercypher-backend

  message-service: # done
    container_name: message-service
    build:
      dockerfile: ./message-service/dockerfile
    ports:
      - "50052:50052"
    depends_on:
      - kafka
    env_file:
      - ./message-service/.env
    environment:
      - KAFKA_BROKERS=kafka:29092
      - GATEWAY_ADDRESS=api-gateway:50051
    networks:
      - mercypher-backend


networks:
  mercypher-backend:
    driver: bridge
