services:
  user-service:
    container_name: user-service
    build:
      context: ./
      dockerfile: ./user-service/Dockerfile
    ports:
      - "50054:50054"
    depends_on:
      - user-db
      - redis
    env_file:
      - ./user-service/.env.dev
    environment:
      ENVIRONMENT: "dev"
    networks:
      - mercypher-backend

  user-db:
    container_name: user-db
    image: postgres
    env_file:
      - ./user-service/.env.dev
    # volumes:
      # -
    ports:
      - "5432:5432"
    networks:
      - mercypher-backend

  session-service:
    container_name: session-service
    build:
      context: ./
      dockerfile: ./session-service/Dockerfile
    ports:
      - "50055:50055"
    depends_on:
      - redis
    env_file:
      - ./session-service/.env.dev
    environment:
      ENVIRONMENT: "dev"
    networks:
      - mercypher-backend

  redis:
    container_name: redis
    image: lukadervisevic/mercypher-redis:1.3
    ports:
      - "6379:6379"
    command: ["redis-server", "/etc/redis/redis.conf"]

    networks:
      - mercypher-backend

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - ./kafka/.env
    post_start: # !!!
      - command: kafka-topics --create --topic "chat-messages-v1" --if-not-exists --bootstrap-server localhost:9092
    networks:
      - mercypher-backend

  message-service:
    container_name: message-service
    build:
      # context: ./message-service
      dockerfile: ./message-service/dockerfile
    ports:
      - "50052:50052"
    depends_on:
      - kafka
    env_file:
      - ./message-service/.env
    networks:
      - mercypher-backend

networks:
  mercypher-backend:
    driver: bridge
