name: User service CI/CD

on:
  push:
    paths: "user-service/**"
    branches: ["test"]

  pull_request:
    paths: "user-service/**"
    branches: ["test"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      next_ver: ${{steps.semver.outputs.next}}
    permissions:
      contents: write
    steps:
      - name: Copying codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: blob:none

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Get Next Version
        uses: ietf-tools/semver-action@v1
        id: semver
        with:
          token: ${{secrets.ACTIONS_TOKEN}}
          branch: main
          noVersionBumpBehavior: silent

      - name: Create next_ver
        if: steps.semver.outputs.next != ''
        run: |
          echo "next_ver=${{steps.semver.outputs.next}}" >> "$GITHUB_OUTPUT"

      - name: Create a tag
        if: steps.semver.outputs.next != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{steps.semver.outputs.next}}
          git push origin ${{steps.semver.outputs.next}}

  docker:
    runs-on: ubuntu-latest
    needs: build

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli-ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Build user service docker image
        if: needs.build.outputs.next_ver != ''
        run: |
          echo "Building user service image with version ${{needs.build.outputs.next_ver}}"
          docker build  -t user-service${{needs.build.outputs.next_ver}} ./user-service/
